### ISSUE TITLE
LV-N "Nerv" Atomic Rocket Motor and the others not producing thrust

### ISSUE THREAD

**Issue by shawnce** [ChrisAdderley/KerbalAtomics#14]
I have been attempting to use KerbalAtomic engines as ones modified by it and I believe NearFutureElectric. When I attempt to use the engine it consumes fuel but produces no thrust. I believe this is fully related to the reactor core not powering up. I see nothing obvious in the logs nor I have I yet found a mod that is potentially conflicting.

In the attached screen shot I started the core and fast forwarded in time a bit (note the depleted fuel). The core shows no information however and the engine produces no thrust despite consuming fuel.

Anyway curious if this is a know issue with a particular mod, etc. I will duplicate again (when I can get time) to capture a log for review.

<img width="503" alt="screen shot 2016-11-12 at 10 26 59 am" src="https://cloud.githubusercontent.com/assets/352255/20250819/dc3e3e66-a9c7-11e6-8648-818a8051d2a6.png">

**Comment by ChrisAdderley** [comment]
Stage the engine and try again ;)
