### ISSUE TITLE
High EnrichedUranium consumption rate on LV-N 'Nerv' with NFE

### ISSUE THREAD

**Issue by klugeh01** [ChrisAdderley/KerbalAtomics#18]
The Nerv consumes EnrichedUranium at a rate about 10x higher than the NTRs from this mod when Near Future Electrical is installed (for the FissionReactor modules on NTRs), while output rate of Depleted Fuel remains similar to other NTRs:

`...
INPUT_RESOURCE
  {
  ResourceName = EnrichedUranium
  Ratio = 0.0027
  FlowMode = NO_FLOW
  }
OUTPUT_RESOURCE
  {
  ResourceName = DepletedFuel
  Ratio = 0.00027
  DumpExcess = false
  FlowMode = NO_FLOW
  }
...`

**Comment by ChrisAdderley** [comment]
Resolved in 17ae400
