### ISSUE TITLE
Kerbal Atomics VSR NTR Patch

### ISSUE THREAD

**Issue by Stratickus** [ChrisAdderley/KerbalAtomics#20]
The file hydrogenNTRsVen within Kerbal Atomics > Patches > NTR is missing the .cfg extension.

Additionally, within that patch for `PART[PoodleM]`, the `MODULE[ModuleEngines]` is used, where `MODULE[ModuleEnginesFX]` is used for the parent part config.

From VSR v1.9.6

Cheers,

**Comment by ChrisAdderley** [comment]
Resolved with significant changes to LH2 and LF patching methods.
