### ISSUE TITLE
Kerbal Atomics SQUAD NTR Patch

### ISSUE THREAD

**Issue by Stratickus** [ChrisAdderley/KerbalAtomics#23]
When using the file hydrogenNTRsSQUAD within Kerbal Atomics > Patches > NTR, the new module `EFFECTS` raises the exhaust plume on the LV-N above and outside the bell. Recommend lowering it. 

For reference, the stock part config has the z `fxOffset` at 1.6. However, this is with the old `ModuleEngines` not the new `ModuleEnginesFX` and `EFFECTS.`

Additionally, when the file KerbalAtomicsNFE within Kerbal Atomics > Extras > NearFutureElectricaNTRs is also used, the above noted 'high' exhaust plume is only present when the reactor is activated. With the reactor deactivated the plume is narrowed and contained within the bell.

Probably a separate issue, but I would expect there to be no plume at all with the reactor deactivated. I believe it is not intended for the motor to work and/or thrust be produced at all with this extra patch. I have seen that the LV-N is not the only engine that behaves this way, so I imagine the problem has to do with stock limitations.

Cheers,

**Comment by ChrisAdderley** [comment]
The second part I can't do much about. It's fairly important though to have "some" kinda plume, because the player needs to know that propellant is flowing through the reactor even if it's off.

**Comment by Stratickus** [comment]
That makes sense. I did not think that the propellant was being 'ejected' out of the reactor without combustion per se.

**Comment by ChrisAdderley** [comment]
Resolved in upcoming version
