### ISSUE TITLE
Eel and Neptune engines have same mass, thrust, fuel consumption

### ISSUE THREAD

**Issue by GHrynk** [ChrisAdderley/KerbalAtomics#33]
The Eel and Neptune in KA 0.4.0 appear to have some duplicate specs, including mass, thrust, and fuel consumption, despite the obvious differences in sizes.  At first glance, this looks like a transcription error - preliminary specs from Forum post on 18 April 2017 appear to fit more logically.

I installed the complete NFT set, plus KA, Heat Control, and CTT as of 17 June.

**Comment by ChrisAdderley** [comment]
Fix in testing and slated for 0.4.1
