### ISSUE TITLE
UnityEngine DLL's in CryoTanks Plugins folder

### ISSUE THREAD

**Issue by PiezPiedPy** [ChrisAdderley/KerbalAtomics#52]
The UnityEngine dll's are present in the CryoTanks/Plugins folder ??
Also the debug symbols file for SimpleBoiloff.dll is also present.

**Comment by ChrisAdderley** [comment]
I can't reproduce this from the latest (0.5.0) release:
```
➜  GameData ls -lr CryoTanks/Plugins
total 40
-rw-r--r--@ 1 cadderley  staff  18432 11 Apr 10:36 SimpleBoiloff.dll
➜  GameData
```

**Comment by PiezPiedPy** [comment]
look in the zip from the releases page on GitHub ;)

**Comment by PiezPiedPy** [comment]
![screenshot 2](https://user-images.githubusercontent.com/17555434/41673251-41319c6a-74b4-11e8-90c0-55ac700c514b.png)

**Comment by ChrisAdderley** [comment]
That zip is way outdated, use the canonical download locations on the forum thread. The newest version (compare that and `master`) is 0.5.0.
