### ISSUE TITLE
RS+ Cherenkov not getting LH2 patch

### ISSUE THREAD

**Issue by Rodg88** [ChrisAdderley/KerbalAtomics#85]
The Cherenkov nuke from RS+ isn't getting patched by KS to use hydrogen.

A ~600isp LF mode would be cool too, since it's a restock NERV-alike and that's what KA does to the NERV

**Comment by ChrisAdderley** [comment]
This will be addressed once Restock 1.1.0+ is released.

**Comment by ChrisAdderley** [comment]
Actually just a note - was it not getting patched at all even with the Extras installed? Default behaviour is to only patch stock, other support must be installed.

**Comment by ChrisAdderley** [comment]
Released as part of 1.1.4
